# Product 环境专用配置示例，请根据实际情况修改
# 这里的配置会覆盖 application.yml 中的同名配置

spring:
  servlet:
    multipart:
      location: /ruoyi/server/temp
  datasource:
    dynamic:
      datasource:
        master:
          driverClassName: org.postgresql.Driver
          url: "jdbc:postgresql://[IP_ADDRESS]/kmatrix?currentSchema=public&reWriteBatchedInserts=true&sslmode=disable"
          username: kmatrix
          password: [PASSWORD]
  data:
    redis:
      database: 10

logging:
  level:
    dev.langchain4j: INFO
    org.dromara.ai: INFO

# AI 配置
ai:
  file-store:
    local-path: /ky/kmatrix/uploads
  unified-embedding-model: true
  reranker:
    model-path: /ky/kmatrix/reranker/bge-reranker-v2-m3/onnx/model_int8.onnx
    tokenizer-path: /ky/kmatrix/reranker/bge-reranker-v2-m3/tokenizer.json

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 2
  # Netty线程池数量
  nettyThreads: 32
  # 单节点配置
  singleServerConfig:
    # 客户端名称 不能用中文
    clientName: KMatrix
    # 最小空闲连接数
    connectionMinimumIdleSize: 32
    # 连接池大小
    connectionPoolSize: 64
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50
