package org.dromara.ai.service.impl;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import lombok.RequiredArgsConstructor;
import org.dromara.ai.domain.KmApp;
import org.dromara.ai.domain.KmAppKnowledge;
import org.dromara.ai.domain.KmAppVersion;
import org.dromara.ai.domain.bo.KmAppBo;
import org.dromara.ai.domain.vo.KmAppVo;
import org.dromara.ai.domain.vo.config.AppSnapshot;
import org.dromara.ai.mapper.KmAppKnowledgeMapper;
import org.dromara.ai.mapper.KmAppMapper;
import org.dromara.ai.mapper.KmAppVersionMapper;
import org.dromara.ai.service.IKmAppService;
import org.dromara.common.core.utils.MapstructUtils;
import org.dromara.common.core.utils.StringUtils;
import org.dromara.common.mybatis.core.page.PageQuery;
import org.dromara.common.mybatis.core.page.TableDataInfo;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

/**
 * AI应用Service业务层处理
 *
 * @author Mahone
 * @date 2025-12-27
 */
@RequiredArgsConstructor
@Service
public class KmAppServiceImpl implements IKmAppService {

    private final KmAppMapper baseMapper;
    private final KmAppVersionMapper versionMapper;
    private final KmAppKnowledgeMapper appKnowledgeMapper;

    /**
     * 查询AI应用
     */
    @Override
    public KmAppVo queryById(Long appId) {
        return baseMapper.selectVoById(appId);
    }

    /**
     * 查询AI应用列表
     */
    @Override
    public TableDataInfo<KmAppVo> queryPageList(KmAppBo bo, PageQuery pageQuery) {
        LambdaQueryWrapper<KmApp> lqw = buildQueryWrapper(bo);
        Page<KmAppVo> result = baseMapper.selectVoPage(pageQuery.build(), lqw);
        return TableDataInfo.build(result);
    }

    /**
     * 查询AI应用列表
     */
    @Override
    public List<KmAppVo> queryList(KmAppBo bo) {
        LambdaQueryWrapper<KmApp> lqw = buildQueryWrapper(bo);
        return baseMapper.selectVoList(lqw);
    }

    private LambdaQueryWrapper<KmApp> buildQueryWrapper(KmAppBo bo) {
        LambdaQueryWrapper<KmApp> lqw = new LambdaQueryWrapper<>();
        lqw.like(StringUtils.isNotBlank(bo.getAppName()), KmApp::getAppName, bo.getAppName());
        lqw.eq(StringUtils.isNotBlank(bo.getAppType()), KmApp::getAppType, bo.getAppType());
        lqw.eq(StringUtils.isNotBlank(bo.getStatus()), KmApp::getStatus, bo.getStatus());
        return lqw;
    }

    /**
     * 新增AI应用
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public String insertByBo(KmAppBo bo) {
        KmApp add = MapstructUtils.convert(bo, KmApp.class);
        // Ensure ID is generated by MyBatis-Plus (ASSIGN_ID)
        add.setAppId(null);
        boolean flag = baseMapper.insert(add) > 0;
        if (flag) {
            bo.setAppId(add.getAppId());
            saveKnowledgeMapping(add.getAppId(), bo.getKnowledgeIds());
            return add.getAppId().toString();
        }
        return null;
    }

    /**
     * 修改AI应用
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean updateByBo(KmAppBo bo) {
        KmApp update = MapstructUtils.convert(bo, KmApp.class);
        boolean flag = baseMapper.updateById(update) > 0;
        if (flag) {
            saveKnowledgeMapping(update.getAppId(), bo.getKnowledgeIds());
        }
        return flag;
    }

    /**
     * 保存知识库映射
     */
    private void saveKnowledgeMapping(Long appId, String knowledgeIds) {
        if (appId == null) {
            return;
        }
        // 删除旧的关联
        appKnowledgeMapper.delete(new LambdaQueryWrapper<KmAppKnowledge>().eq(KmAppKnowledge::getAppId, appId));

        if (StringUtils.isBlank(knowledgeIds)) {
            return;
        }

        List<Long> kbIds = StrUtil.split(knowledgeIds, ',', true, true).stream()
                .map(Long::valueOf)
                .collect(Collectors.toList());

        if (CollUtil.isNotEmpty(kbIds)) {
            List<KmAppKnowledge> list = new ArrayList<>();
            for (int i = 0; i < kbIds.size(); i++) {
                KmAppKnowledge mapping = new KmAppKnowledge();
                mapping.setAppId(appId);
                mapping.setKnowledgeId(kbIds.get(i));
                mapping.setSort(i);
                list.add(mapping);
            }
            appKnowledgeMapper.insertBatch(list);
        }
    }

    /**
     * 校验并批量删除AI应用信息
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean deleteWithValidByIds(Collection<Long> ids, Boolean isValid) {
        if (isValid) {
            // TODO: 校验逻辑，例如应用是否正在被使用
        }
        // 删除关联
        appKnowledgeMapper.delete(new LambdaQueryWrapper<KmAppKnowledge>().in(KmAppKnowledge::getAppId, ids));
        versionMapper.delete(new LambdaQueryWrapper<KmAppVersion>().in(KmAppVersion::getAppId, ids));

        return baseMapper.deleteByIds(ids) > 0;
    }

    /**
     * 发布应用 (创建快照)
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean publishApp(Long appId) {
        KmApp app = baseMapper.selectById(appId);
        if (app == null) {
            return false;
        }

        // 更新应用状态为发布
        app.setStatus("1");
        baseMapper.updateById(app);

        // 创建历史版本快照
        KmAppVersion version = new KmAppVersion();
        version.setAppId(appId);
        // 获取当前最大版本号 + 1
        Integer maxVersion = versionMapper
                .selectCount(new LambdaQueryWrapper<KmAppVersion>().eq(KmAppVersion::getAppId, appId)).intValue();
        version.setVersion(maxVersion + 1);
        version.setCreateTime(new Date());
        // createBy 由 MyBatis 自动填充或 SecurityContext 获取，这里手动设置一下当前更新人
        version.setCreateBy(app.getUpdateBy());

        // 构建快照
        AppSnapshot snapshot = new AppSnapshot();
        snapshot.setAppName(app.getAppName());
        snapshot.setDescription(app.getDescription());
        snapshot.setIcon(app.getIcon());
        snapshot.setAppType(app.getAppType());
        snapshot.setPrologue(app.getPrologue());
        snapshot.setModelSetting(app.getModelSetting());
        snapshot.setKnowledgeSetting(app.getKnowledgeSetting());
        snapshot.setWorkflowConfig(app.getWorkflowConfig());
        snapshot.setGraphData(app.getGraphData());
        snapshot.setDslData(app.getDslData());
        snapshot.setModelId(app.getModelId());

        version.setAppSnapshot(snapshot);
        version.setRemark("发布版本 " + version.getVersion());

        return versionMapper.insert(version) > 0;
    }
}
