package org.dromara.ai.service.impl;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import lombok.RequiredArgsConstructor;
import org.dromara.ai.domain.KmApp;
import org.dromara.ai.domain.KmAppKnowledge;
import org.dromara.ai.domain.KmAppVersion;
import org.dromara.ai.domain.bo.KmAppBo;
import org.dromara.ai.domain.vo.KmAppVo;
import org.dromara.ai.domain.vo.config.AppSnapshot;
import org.dromara.ai.mapper.KmAppKnowledgeMapper;
import org.dromara.ai.mapper.KmAppMapper;
import org.dromara.ai.mapper.KmAppVersionMapper;
import org.dromara.ai.service.IKmAppService;
import org.dromara.ai.workflow.core.WorkflowConfig;
import org.dromara.common.core.utils.MapstructUtils;
import org.dromara.common.core.utils.StringUtils;
import org.dromara.common.mybatis.core.page.PageQuery;
import org.dromara.common.mybatis.core.page.TableDataInfo;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.dromara.common.json.utils.JsonUtils;
import org.dromara.ai.service.IKmAppTokenService;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

/**
 * AI应用Service业务层处理
 *
 * @author Mahone
 * @date 2025-12-27
 */
@RequiredArgsConstructor
@Service
public class KmAppServiceImpl implements IKmAppService {

    private final KmAppMapper baseMapper;
    private final KmAppVersionMapper versionMapper;
    private final KmAppKnowledgeMapper appKnowledgeMapper;
    private final IKmAppTokenService appTokenService;
    private final org.dromara.ai.mapper.KmChatSessionMapper chatSessionMapper;
    private final org.dromara.ai.mapper.KmChatMessageMapper chatMessageMapper;

    /**
     * 查询AI应用
     */
    @Override
    public KmAppVo queryById(Long appId) {
        KmAppVo vo = baseMapper.selectVoById(appId);
        if (vo != null) {
            List<KmAppKnowledge> list = appKnowledgeMapper.selectList(
                    new LambdaQueryWrapper<KmAppKnowledge>().eq(KmAppKnowledge::getAppId, appId));
            if (CollUtil.isNotEmpty(list)) {
                String ids = list.stream()
                        .map(k -> k.getKnowledgeId().toString())
                        .collect(Collectors.joining(","));
                vo.setKnowledgeIds(ids);
            }
        }
        return vo;
    }

    /**
     * 查询AI应用列表
     */
    @Override
    public TableDataInfo<KmAppVo> queryPageList(KmAppBo bo, PageQuery pageQuery) {
        LambdaQueryWrapper<KmApp> lqw = buildQueryWrapper(bo);
        Page<KmAppVo> result = baseMapper.selectVoPage(pageQuery.build(), lqw);
        return TableDataInfo.build(result);
    }

    /**
     * 查询AI应用列表
     */
    @Override
    public List<KmAppVo> queryList(KmAppBo bo) {
        LambdaQueryWrapper<KmApp> lqw = buildQueryWrapper(bo);
        return baseMapper.selectVoList(lqw);
    }

    private LambdaQueryWrapper<KmApp> buildQueryWrapper(KmAppBo bo) {
        LambdaQueryWrapper<KmApp> lqw = new LambdaQueryWrapper<>();
        lqw.like(StringUtils.isNotBlank(bo.getAppName()), KmApp::getAppName, bo.getAppName());
        lqw.eq(StringUtils.isNotBlank(bo.getAppType()), KmApp::getAppType, bo.getAppType());
        lqw.eq(StringUtils.isNotBlank(bo.getStatus()), KmApp::getStatus, bo.getStatus());
        return lqw;
    }

    /**
     * 新增AI应用
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public String insertByBo(KmAppBo bo) {
        KmApp add = MapstructUtils.convert(bo, KmApp.class);

        // 如果是工作流类型应用,校验工作流配置 -- 改在发布逻辑校验，保存草稿放行
        // if ("2".equals(add.getAppType()) && StringUtils.isNotBlank(add.getDslData()))
        // {
        // WorkflowConfig config = JsonUtils.parseObject(add.getDslData(),
        // WorkflowConfig.class);
        // config.validate();
        // }

        // Ensure ID is generated by MyBatis-Plus (ASSIGN_ID)
        add.setAppId(null);
        boolean flag = baseMapper.insert(add) > 0;
        if (flag) {
            bo.setAppId(add.getAppId());
            saveKnowledgeMapping(add.getAppId(), bo.getKnowledgeIds());
            // 创建默认Token
            appTokenService.createDefaultToken(add.getAppId(), add.getAppName());
            return add.getAppId().toString();
        }
        return null;
    }

    /**
     * 修改AI应用
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean updateByBo(KmAppBo bo) {
        KmApp update = MapstructUtils.convert(bo, KmApp.class);

        // 找到应用数据
        KmApp app = baseMapper.selectById(update.getAppId());
        if (app == null) {
            throw new RuntimeException("应用不存在");
        }
        // 如果是工作流类型应用,校验工作流配置 -- 改在发布逻辑校验，保存草稿放行
        // if ("2".equals(app.getAppType()) &&
        // StringUtils.isNotBlank(update.getDslData())) {
        // WorkflowConfig config = JsonUtils.parseObject(update.getDslData(),
        // WorkflowConfig.class);
        // config.validate();
        // }

        boolean flag = baseMapper.updateById(update) > 0;
        if (flag) {
            saveKnowledgeMapping(update.getAppId(), bo.getKnowledgeIds());
        }
        return flag;
    }

    /**
     * 保存知识库映射
     */
    private void saveKnowledgeMapping(Long appId, String knowledgeIds) {
        if (appId == null) {
            return;
        }
        // 删除旧的关联
        appKnowledgeMapper.delete(new LambdaQueryWrapper<KmAppKnowledge>().eq(KmAppKnowledge::getAppId, appId));

        if (StringUtils.isBlank(knowledgeIds)) {
            return;
        }

        List<Long> kbIds = StrUtil.split(knowledgeIds, ',', true, true).stream()
                .map(Long::valueOf)
                .collect(Collectors.toList());

        if (CollUtil.isNotEmpty(kbIds)) {
            List<KmAppKnowledge> list = new ArrayList<>();
            for (int i = 0; i < kbIds.size(); i++) {
                KmAppKnowledge mapping = new KmAppKnowledge();
                mapping.setAppId(appId);
                mapping.setKnowledgeId(kbIds.get(i));
                mapping.setSort(i);
                list.add(mapping);
            }
            appKnowledgeMapper.insertBatch(list);
        }
    }

    /**
     * 校验并批量删除AI应用信息
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean deleteWithValidByIds(Collection<Long> ids, Boolean isValid) {
        if (isValid) {
            // TODO: 校验逻辑，例如应用是否正在被使用
        }
        // 删除关联
        appKnowledgeMapper.delete(new LambdaQueryWrapper<KmAppKnowledge>().in(KmAppKnowledge::getAppId, ids));
        versionMapper.delete(new LambdaQueryWrapper<KmAppVersion>().in(KmAppVersion::getAppId, ids));

        return baseMapper.deleteByIds(ids) > 0;
    }

    /**
     * 发布应用 (创建快照)
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean publishApp(Long appId, String remark) {
        KmApp app = baseMapper.selectById(appId);
        if (app == null) {
            return false;
        }

        // 如果是工作流类型应用,校验工作流配置
        if ("2".equals(app.getAppType()) && StringUtils.isNotBlank(app.getDslData())) {
            WorkflowConfig config = JsonUtils.parseObject(app.getDslData(), WorkflowConfig.class);
            config.validate();
        }

        // 查询最新发布版本,对比 DSL 是否有变更
        KmAppVersion latestVersion = versionMapper.selectOne(
                new LambdaQueryWrapper<KmAppVersion>()
                        .eq(KmAppVersion::getAppId, appId)
                        .orderByDesc(KmAppVersion::getVersion)
                        .last("LIMIT 1"));

        if (latestVersion != null && latestVersion.getAppSnapshot() != null) {
            String lastDslData = latestVersion.getAppSnapshot().getDslData();
            String currentDslData = app.getDslData();

            // 对比 DSL 数据(忽略空白字符差异)
            if (StringUtils.isNotBlank(lastDslData) && StringUtils.isNotBlank(currentDslData)) {
                String normalizedLast = lastDslData.replaceAll("\\s+", "");
                String normalizedCurrent = currentDslData.replaceAll("\\s+", "");

                if (normalizedLast.equals(normalizedCurrent)) {
                    throw new RuntimeException("工作流配置无变更,无需发布");
                }
            }
        }

        // 更新应用状态为发布
        app.setStatus("1");
        baseMapper.updateById(app);

        // 创建历史版本快照
        KmAppVersion version = new KmAppVersion();
        version.setAppId(appId);
        // 获取当前最大版本号 + 1
        Integer maxVersion = versionMapper
                .selectCount(new LambdaQueryWrapper<KmAppVersion>().eq(KmAppVersion::getAppId, appId)).intValue();
        version.setVersion(maxVersion + 1);
        version.setCreateTime(new Date());
        // createBy 由 MyBatis 自动填充或 SecurityContext 获取，这里手动设置一下当前更新人
        version.setCreateBy(app.getUpdateBy());

        // 构建快照
        AppSnapshot snapshot = new AppSnapshot();
        snapshot.setAppName(app.getAppName());
        snapshot.setDescription(app.getDescription());
        snapshot.setIcon(app.getIcon());
        snapshot.setAppType(app.getAppType());
        snapshot.setPrologue(app.getPrologue());
        snapshot.setModelSetting(app.getModelSetting());
        snapshot.setKnowledgeSetting(app.getKnowledgeSetting());
        snapshot.setWorkflowConfig(app.getWorkflowConfig());
        snapshot.setGraphData(app.getGraphData());
        snapshot.setDslData(app.getDslData());
        snapshot.setModelId(app.getModelId());

        version.setAppSnapshot(snapshot);
        version.setRemark(StringUtils.isBlank(remark) ? "发布版本 " + version.getVersion() : remark);

        return versionMapper.insert(version) > 0;
    }

    /**
     * 获取应用的最新发布版本快照
     */
    @Override
    public AppSnapshot getLatestPublishedSnapshot(Long appId) {
        KmAppVersion latestVersion = versionMapper.selectOne(
                new LambdaQueryWrapper<KmAppVersion>()
                        .eq(KmAppVersion::getAppId, appId)
                        .orderByDesc(KmAppVersion::getVersion)
                        .last("LIMIT 1"));

        return latestVersion != null ? latestVersion.getAppSnapshot() : null;
    }

    /**
     * 更新公开访问开关
     */
    @Override
    public Boolean updatePublicAccess(Long appId, String publicAccess) {
        KmApp app = new KmApp();
        app.setAppId(appId);
        app.setPublicAccess(publicAccess);
        return baseMapper.updateById(app) > 0;
    }

    /**
     * 获取应用统计数据
     */
    @Override
    public org.dromara.ai.domain.vo.KmAppStatisticsVo getAppStatistics(Long appId, String period) {
        if (appId == null) {
            return new org.dromara.ai.domain.vo.KmAppStatisticsVo();
        }

        // 计算时间范围
        Date startTime = calculateStartTime(period);

        // 统计数据
        org.dromara.ai.domain.vo.KmAppStatisticsVo stats = new org.dromara.ai.domain.vo.KmAppStatisticsVo();

        // 1. 用户总数 (基于会话去重)
        // SELECT COUNT(DISTINCT user_id) FROM km_chat_session WHERE app_id = ? AND
        // create_time >= ?
        // 这里暂时简化为查询会话数，实际应关联用户
        long userCount = chatSessionMapper.selectCount(
                new LambdaQueryWrapper<org.dromara.ai.domain.KmChatSession>()
                        .eq(org.dromara.ai.domain.KmChatSession::getAppId, appId)
                        .ge(startTime != null, org.dromara.ai.domain.KmChatSession::getCreateTime, startTime));
        stats.setUserCount(userCount);
        stats.setUserCountDelta(0L); // 暂不计算环比

        // 2. 提问次数 (消息数)
        // 由于 KmChatMessage 没有 appId，需要关联 KmChatSession
        // 简化: 先查出该应用下的所有会话ID, 再查消息数
        // 注意:这里如果会话很多可能有性能问题, 理想情况应该在 Message 表冗余 appId 或使用 JOIN
        // 这里暂时使用 EXISTS 子查询 (MyBatis-Plus apply)
        long questionCount = chatMessageMapper.selectCount(
                new LambdaQueryWrapper<org.dromara.ai.domain.KmChatMessage>()
                        .eq(org.dromara.ai.domain.KmChatMessage::getRole, "user") // 只统计用户提问
                        .apply("session_id IN (SELECT session_id FROM km_chat_session WHERE app_id = {0}" +
                                (startTime != null ? " AND create_time >= {1}" : "") + ")",
                                appId, startTime));
        stats.setQuestionCount(questionCount);

        // 3. Tokens 总数 (需要消息表有 tokens 字段，假设有)
        // 暂且置为 0，需确认 KmChatMessage 是否有 tokens 字段
        stats.setTokensTotal(0L);

        // 4. 用户满意度
        org.dromara.ai.domain.vo.KmAppStatisticsVo.Satisfaction satisfaction = new org.dromara.ai.domain.vo.KmAppStatisticsVo.Satisfaction();
        satisfaction.setLike(0L);
        satisfaction.setDislike(0L);
        stats.setSatisfaction(satisfaction);

        // 5. 模拟趋势数据 (后续对接真实数据)
        stats.setUserTrend(new java.util.HashMap<>());
        stats.setQuestionTrend(new java.util.HashMap<>());

        return stats;
    }

    private Date calculateStartTime(String period) {
        Date now = new Date();
        if ("7d".equals(period)) {
            return cn.hutool.core.date.DateUtil.offsetDay(now, -7);
        } else if ("30d".equals(period)) {
            return cn.hutool.core.date.DateUtil.offsetDay(now, -30);
        } else if ("90d".equals(period)) {
            return cn.hutool.core.date.DateUtil.offsetDay(now, -90);
        }
        return null; // 全部
    }
}
