package org.dromara.ai.app.service.impl;

import org.dromara.common.core.utils.MessageUtils;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.date.DateUtil;
import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import lombok.RequiredArgsConstructor;
import org.dromara.ai.app.domain.*;
import org.dromara.ai.app.domain.bo.KmAppBo;
import org.dromara.ai.api.enums.AiAppType;
import org.dromara.ai.app.domain.vo.KmAppStatisticsVo;
import org.dromara.ai.app.domain.vo.KmAppVersionVo;
import org.dromara.ai.app.domain.vo.KmAppVo;
import org.dromara.ai.app.domain.vo.config.AppSnapshot;
import org.dromara.ai.app.mapper.*;
import org.dromara.ai.knowledge.mapper.*;
import org.dromara.ai.knowledge.domain.KmAppKnowledge;
import org.dromara.ai.app.service.IKmAppService;
import org.dromara.ai.workflow.workflow.core.WorkflowConfig;
import org.dromara.common.core.utils.MapstructUtils;
import org.dromara.common.core.utils.StringUtils;
import org.dromara.common.mybatis.core.page.PageQuery;
import org.dromara.common.mybatis.core.page.TableDataInfo;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.dromara.common.json.utils.JsonUtils;
import org.dromara.ai.app.service.IKmAppTokenService;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * AI应用Service业务层处理
 *
 * @author Mahone
 * @date 2025-12-27
 */
@RequiredArgsConstructor
@Service
public class KmAppServiceImpl implements IKmAppService {

    private final KmAppMapper baseMapper;
    private final KmAppVersionMapper versionMapper;
    private final KmAppKnowledgeMapper appKnowledgeMapper;
    private final IKmAppTokenService appTokenService;
    private final KmChatSessionMapper chatSessionMapper;
    private final KmChatMessageMapper chatMessageMapper;
    private final KmAppAccessStatMapper appAccessStatMapper;
    private final org.dromara.ai.app.service.IAppCapabilityService appCapabilityService;


    /**
     * 查询AI应用
     */
    @Override
    public KmAppVo queryById(Long appId) {
        KmAppVo vo = baseMapper.selectVoById(appId);
        if (vo != null) {
            List<KmAppKnowledge> list = appKnowledgeMapper.selectList(
                    new LambdaQueryWrapper<KmAppKnowledge>().eq(KmAppKnowledge::getAppId, appId));
            if (CollUtil.isNotEmpty(list)) {
                String ids = list.stream()
                        .map(k -> k.getKnowledgeId().toString())
                        .collect(Collectors.joining(","));
                vo.setKnowledgeIds(ids);
            }
            vo.setCapabilities(appCapabilityService.getAppCapabilities(appId));
        }
        return vo;
    }

    /**
     * 查询AI应用列表
     */
    @Override
    public TableDataInfo<KmAppVo> queryPageList(KmAppBo bo, PageQuery pageQuery) {
        LambdaQueryWrapper<KmApp> lqw = buildQueryWrapper(bo);
        Page<KmAppVo> result = baseMapper.selectVoPage(pageQuery.build(), lqw);
        return TableDataInfo.build(result);
    }

    /**
     * 查询AI应用列表
     */
    @Override
    public List<KmAppVo> queryList(KmAppBo bo) {
        LambdaQueryWrapper<KmApp> lqw = buildQueryWrapper(bo);
        return baseMapper.selectVoList(lqw);
    }

    private LambdaQueryWrapper<KmApp> buildQueryWrapper(KmAppBo bo) {
        LambdaQueryWrapper<KmApp> lqw = new LambdaQueryWrapper<>();
        lqw.like(StringUtils.isNotBlank(bo.getAppName()), KmApp::getAppName, bo.getAppName());
        lqw.eq(StringUtils.isNotBlank(bo.getAppType()), KmApp::getAppType, bo.getAppType());
        lqw.eq(StringUtils.isNotBlank(bo.getStatus()), KmApp::getStatus, bo.getStatus());
        return lqw;
    }

    /**
     * 新增AI应用
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public String insertByBo(KmAppBo bo) {
        KmApp add = MapstructUtils.convert(bo, KmApp.class);

        // 如果是工作流类型应用,校验工作流配置 -- 改在发布逻辑校验，保存草稿放行
        // if ("2".equals(add.getAppType()) && StringUtils.isNotBlank(add.getDslData()))
        // {
        // WorkflowConfig config = JsonUtils.parseObject(add.getDslData(),
        // WorkflowConfig.class);
        // config.validate();
        // }

        // Ensure ID is generated by MyBatis-Plus (ASSIGN_ID)
        add.setAppId(null);
        boolean flag = baseMapper.insert(add) > 0;
        if (flag) {
            bo.setAppId(add.getAppId());
            saveKnowledgeMapping(add.getAppId(), bo.getKnowledgeIds());
            // 创建默认Token
            appTokenService.createDefaultToken(add.getAppId(), add.getAppName());
            return add.getAppId().toString();
        }
        return null;
    }

    /**
     * 修改AI应用
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean updateByBo(KmAppBo bo) {
        KmApp update = MapstructUtils.convert(bo, KmApp.class);

        // 找到应用数据
        KmApp app = baseMapper.selectById(update.getAppId());
        if (app == null) {
            throw new RuntimeException(MessageUtils.message("ai.msg.app.not_found"));
        }
        // 如果是工作流类型应用,校验工作流配置 -- 改在发布逻辑校验，保存草稿放行
        // if ("2".equals(app.getAppType()) &&
        // StringUtils.isNotBlank(update.getDslData())) {
        // WorkflowConfig config = JsonUtils.parseObject(update.getDslData(),
        // WorkflowConfig.class);
        // config.validate();
        // }

        boolean flag = baseMapper.updateById(update) > 0;
        if (flag) {
            saveKnowledgeMapping(update.getAppId(), bo.getKnowledgeIds());
        }
        return flag;
    }

    /**
     * 保存知识库映射
     */
    private void saveKnowledgeMapping(Long appId, String knowledgeIds) {
        if (appId == null) {
            return;
        }
        // 删除旧的关联
        appKnowledgeMapper.delete(new LambdaQueryWrapper<KmAppKnowledge>().eq(KmAppKnowledge::getAppId, appId));

        if (StringUtils.isBlank(knowledgeIds)) {
            return;
        }

        List<Long> kbIds = StrUtil.split(knowledgeIds, ',', true, true).stream()
                .map(Long::valueOf)
                .collect(Collectors.toList());

        if (CollUtil.isNotEmpty(kbIds)) {
            List<KmAppKnowledge> list = new ArrayList<>();
            for (int i = 0; i < kbIds.size(); i++) {
                KmAppKnowledge mapping = new KmAppKnowledge();
                mapping.setAppId(appId);
                mapping.setKnowledgeId(kbIds.get(i));
                mapping.setSort(i);
                list.add(mapping);
            }
            appKnowledgeMapper.insertBatch(list);
        }
    }

    /**
     * 校验并批量删除AI应用信息
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean deleteWithValidByIds(Collection<Long> ids, Boolean isValid) {
        if (isValid) {
            // TODO: 校验逻辑，例如应用是否正在被使用
        }
        // 删除关联
        appKnowledgeMapper.delete(new LambdaQueryWrapper<KmAppKnowledge>().in(KmAppKnowledge::getAppId, ids));
        versionMapper.delete(new LambdaQueryWrapper<KmAppVersion>().in(KmAppVersion::getAppId, ids));

        return baseMapper.deleteByIds(ids) > 0;
    }

    /**
     * 发布应用 (创建快照)
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public Boolean publishApp(Long appId, String remark) {
        KmApp app = baseMapper.selectById(appId);
        if (app == null) {
            return false;
        }

        // 如果是工作流类型或固定模板应用,校验工作流配置
        if ((AiAppType.CUSTOM_WORKFLOW.getCode().equals(app.getAppType())
                || AiAppType.FIXED_TEMPLATE.getCode().equals(app.getAppType()))
                && StringUtils.isNotBlank(app.getDslData())) {
            WorkflowConfig config = JsonUtils.parseObject(app.getDslData(), WorkflowConfig.class);
            config.validate();
        }

        // 查询最新发布版本,对比 DSL 是否有变更
        KmAppVersion latestVersion = versionMapper.selectOne(
                new LambdaQueryWrapper<KmAppVersion>()
                        .eq(KmAppVersion::getAppId, appId)
                        .orderByDesc(KmAppVersion::getVersion)
                        .last("LIMIT 1"));

        if (latestVersion != null && latestVersion.getAppSnapshot() != null) {
            String lastDslData = latestVersion.getAppSnapshot().getDslData();
            String currentDslData = app.getDslData();

            // 对比 DSL 数据(忽略空白字符差异)
            if (StringUtils.isNotBlank(lastDslData) && StringUtils.isNotBlank(currentDslData)) {
                String normalizedLast = lastDslData.replaceAll("\\s+", "");
                String normalizedCurrent = currentDslData.replaceAll("\\s+", "");

                if (normalizedLast.equals(normalizedCurrent)) {
                    throw new RuntimeException(MessageUtils.message("ai.msg.workflow.no_changes"));
                }
            }
        }

        // 更新应用状态为发布
        app.setStatus("1");
        baseMapper.updateById(app);

        // 创建历史版本快照
        KmAppVersion version = new KmAppVersion();
        version.setAppId(appId);
        // 获取当前最大版本号 + 1
        Integer maxVersion = versionMapper
                .selectCount(new LambdaQueryWrapper<KmAppVersion>().eq(KmAppVersion::getAppId, appId)).intValue();
        version.setVersion(maxVersion + 1);
        version.setCreateTime(new Date());
        // createBy 由 MyBatis 自动填充或 SecurityContext 获取，这里手动设置一下当前更新人
        version.setCreateBy(app.getUpdateBy());

        // 构建快照
        AppSnapshot snapshot = new AppSnapshot();
        snapshot.setAppName(app.getAppName());
        snapshot.setDescription(app.getDescription());
        snapshot.setIcon(app.getIcon());
        snapshot.setAppType(app.getAppType());
        snapshot.setPrologue(app.getPrologue());
        snapshot.setModelSetting(app.getModelSetting());
        snapshot.setKnowledgeSetting(app.getKnowledgeSetting());
        snapshot.setWorkflowConfig(app.getWorkflowConfig());
        snapshot.setGraphData(app.getGraphData());
        snapshot.setDslData(app.getDslData());
        snapshot.setModelId(app.getModelId());

        version.setAppSnapshot(snapshot);
        version.setRemark(StringUtils.isBlank(remark) ? "发布版本 " + version.getVersion() : remark);

        return versionMapper.insert(version) > 0;
    }

    /**
     * 获取应用的最新发布版本快照
     */
    @Override
    public AppSnapshot getLatestPublishedSnapshot(Long appId) {
        KmAppVersion latestVersion = versionMapper.selectOne(
                new LambdaQueryWrapper<KmAppVersion>()
                        .eq(KmAppVersion::getAppId, appId)
                        .orderByDesc(KmAppVersion::getVersion)
                        .last("LIMIT 1"));

        return latestVersion != null ? latestVersion.getAppSnapshot() : null;
    }

    /**
     * 更新公开访问开关
     */
    @Override
    public Boolean updatePublicAccess(Long appId, String publicAccess) {
        KmApp app = new KmApp();
        app.setAppId(appId);
        app.setPublicAccess(publicAccess);
        return baseMapper.updateById(app) > 0;
    }

    /**
     * 获取应用统计数据
     */
    @Override
    public KmAppStatisticsVo getAppStatistics(Long appId, String period) {
        if (appId == null) {
            return new KmAppStatisticsVo();
        }

        // 计算时间范围
        Date startTime = calculateStartTime(period);

        // 统计数据
        KmAppStatisticsVo stats = new KmAppStatisticsVo();

        // 1. 用户总数
        long userCount = 0;
        long questionCount = 0;
        long tokensTotal = 0;
        KmAppStatisticsVo.Satisfaction satisfaction = new KmAppStatisticsVo.Satisfaction();
        satisfaction.setLike(0L);
        satisfaction.setDislike(0L);

        if (startTime == null) {
            // 全时段统计: 优先从 km_app_access_stat 获取
            List<KmAppAccessStat> statsList = appAccessStatMapper.selectList(
                new LambdaQueryWrapper<KmAppAccessStat>().eq(KmAppAccessStat::getAppId, appId));
            
            userCount = statsList.size(); // 记录数即用户数
            for (KmAppAccessStat item : statsList) {
                questionCount += (item.getQuestionCount() != null ? item.getQuestionCount() : 0L);
                tokensTotal += (item.getTokenCount() != null ? item.getTokenCount() : 0L);
                satisfaction.setLike(satisfaction.getLike() + (item.getLikeCount() != null ? item.getLikeCount() : 0L));
                satisfaction.setDislike(satisfaction.getDislike() + (item.getDislikeCount() != null ? item.getDislikeCount() : 0L));
            }
        } else {
            // 特定周期统计: 维持原逻辑 (从消息/会话实时计算)
            userCount = chatSessionMapper.selectCount(
                    new LambdaQueryWrapper<KmChatSession>()
                            .eq(KmChatSession::getAppId, appId)
                            .ge(KmChatSession::getCreateTime, startTime));

            questionCount = chatMessageMapper.selectCount(
                    new LambdaQueryWrapper<KmChatMessage>()
                            .eq(KmChatMessage::getRole, "user")
                            .apply("session_id IN (SELECT session_id FROM km_chat_session WHERE app_id = {0} AND create_time >= {1})",
                                    appId, startTime));

            Long tokensSum = chatMessageMapper.sumTotalTokensByAppId(appId, startTime);
            tokensTotal = tokensSum != null ? tokensSum : 0L;

            List<Map<String, Object>> feedbackList = chatMessageMapper.countFeedbackByAppId(appId, startTime);
            if (CollUtil.isNotEmpty(feedbackList)) {
                for (Map<String, Object> map : feedbackList) {
                    Number statusNum = (Number) map.get("status");
                    Long count = map.get("count") != null ? ((Number) map.get("count")).longValue() : 0L;
                    if (statusNum != null) {
                        int status = statusNum.intValue();
                        if (status == 1) {
                            satisfaction.setLike(count);
                        } else if (status == -1) {
                            satisfaction.setDislike(count);
                        }
                    }
                }
            }
        }

        stats.setUserCount(userCount);
        stats.setUserCountDelta(0L);
        stats.setQuestionCount(questionCount);
        stats.setTokensTotal(tokensTotal);
        stats.setSatisfaction(satisfaction);

        // 5. 趋势数据
        Map<String, Long> userTrendMap = new HashMap<>();
        List<Map<String, Object>> userTrendList = chatSessionMapper.getUserTrendByAppId(appId, startTime);
        if (CollUtil.isNotEmpty(userTrendList)) {
            for (Map<String, Object> map : userTrendList) {
                String date = (String) map.get("date");
                Long count = map.get("count") != null ? ((Number) map.get("count")).longValue() : 0L;
                if (date != null) {
                    userTrendMap.put(date, count);
                }
            }
        }
        stats.setUserTrend(userTrendMap);

        Map<String, Long> questionTrendMap = new HashMap<>();
        List<Map<String, Object>> questionTrendList = chatMessageMapper.getQuestionTrendByAppId(appId, startTime);
        if (CollUtil.isNotEmpty(questionTrendList)) {
            for (Map<String, Object> map : questionTrendList) {
                String date = (String) map.get("date");
                Long count = map.get("count") != null ? ((Number) map.get("count")).longValue() : 0L;
                if (date != null) {
                    questionTrendMap.put(date, count);
                }
            }
        }
        stats.setQuestionTrend(questionTrendMap);

        return stats;
    }

    private Date calculateStartTime(String period) {
        Date now = new Date();
        if ("7d".equals(period)) {
            return DateUtil.offsetDay(now, -7);
        } else if ("30d".equals(period)) {
            return DateUtil.offsetDay(now, -30);
        } else if ("90d".equals(period)) {
            return DateUtil.offsetDay(now, -90);
        }
        return null; // 全部
    }

    @Override
    public List<KmAppVersionVo> getPublishHistory(Long appId) {
        List<KmAppVersion> versions = versionMapper.selectList(
                new LambdaQueryWrapper<KmAppVersion>()
                        .eq(KmAppVersion::getAppId, appId)
                        .orderByDesc(KmAppVersion::getVersion));
        return MapstructUtils.convert(versions, KmAppVersionVo.class);
    }

    @Override
    public void updateAccessStat(Long appId, Long userId, Long tokens, Integer likes, Integer dislikes, Integer questions) {
        if (appId == null || userId == null) {
            return;
        }
        // 使用 MyBatis-Plus 生成 ID (如果需要 INSERT)
        Long id = com.baomidou.mybatisplus.core.toolkit.IdWorker.getId();
        appAccessStatMapper.incrementStats(id, appId, userId, 
            tokens != null ? tokens : 0L, 
            likes != null ? likes : 0, 
            dislikes != null ? dislikes : 0, 
            questions != null ? questions : 0);
    }
}
